# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-25 22:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20160625_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='full_name',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
