# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-25 22:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_signup_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='full_name',
        ),
    ]
