# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 19:49
from __future__ import unicode_literals

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20160620_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, height_field=b'height_field', null=True, upload_to=posts.models.upload_location, width_field=b'width_field'),
        ),
    ]
